=== tyler-sommer/resume2/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://tylersommer.pro" xmlns:xs="http://www.w3.org/2001/XMLSchema"  xmlns:tspro="https://tylersommer.pro">
  <xs:element name="resume" type="tspro:resumeType"/>
  <xs:complexType name="qualificationsType">
    <xs:choice>
      <xs:element type="tspro:attributeType" name="attribute" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="profileType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="xs:string" name="section" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="positionType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="xs:string" minOccurs="1" maxOccurs="1" name="company"/>
      <xs:element type="xs:string" minOccurs="1" maxOccurs="1" name="title"/>
      <xs:element type="xs:string" minOccurs="1" maxOccurs="1" name="location"/>
      <xs:element type="xs:string" minOccurs="1" maxOccurs="1" name="from"/>
      <xs:element type="xs:string" minOccurs="1" maxOccurs="1" name="to"/>
      <xs:element type="tspro:descriptionType" minOccurs="1" maxOccurs="1" name="description"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="descriptionType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="xs:string" name="section" maxOccurs="unbounded" minOccurs="1"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="attributeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="type" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="platform"/>
              <xs:enumeration value="language"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="rusty" type="xs:boolean" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="extraType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="kind"  use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="contract"/>
              <xs:enumeration value="hobby"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="experienceType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="tspro:positionType" name="position" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element type="tspro:extraType" name="extra" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="imageType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="src" use="required" type="xs:string"/>
        <xs:attribute name="alt" use="required" type="xs:string"/>
        <xs:attribute name="title" use="required" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="linkType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="href" use="required"/>
        <xs:attribute type="xs:string" name="icon" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="projectType">
    <xs:sequence>
      <xs:element type="xs:string" name="name" maxOccurs="1" minOccurs="1"/>
      <xs:element type="xs:string" name="blurb" maxOccurs="1" minOccurs="0"/>
      <xs:element type="tspro:descriptionType" name="description" maxOccurs="1" minOccurs="1"/>
      <xs:element type="tspro:linkType" name="link" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element type="tspro:imageType" name="image" maxOccurs="1" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="projectsType">
    <xs:choice>
      <xs:element type="tspro:projectType" name="project" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="socialType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="href" use="required" type="xs:string"/>
        <xs:attribute name="icon" use="required" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="linksType">
    <xs:choice>
      <xs:element type="tspro:socialType" name="social" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="resumeType">
    <xs:sequence>
      <xs:element type="xs:string" name="name" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="phone" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="email" minOccurs="1" maxOccurs="1"/>
      <xs:element type="xs:string" name="title" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element type="xs:string" name="description" minOccurs="1" maxOccurs="1"/>
      <xs:element type="tspro:profileType" name="profile" minOccurs="1" maxOccurs="1"/>
      <xs:element type="tspro:experienceType" name="experience" minOccurs="1" maxOccurs="1"/>
      <xs:element type="tspro:projectsType" name="projects" minOccurs="1" maxOccurs="1"/>
      <xs:element type="tspro:qualificationsType" name="qualifications" minOccurs="1" maxOccurs="1"/>
      <xs:element type="tspro:linksType" name="links" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== tyler-sommer/resume2/data.xml
<?xml version="1.0"?>
<resume xmlns="https://tylersommer.pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://tylersommer.pro data.xsd">
    <name>Tyler Sommer</name>
    <phone>(801) 232-1478</phone>
    <email>contact@tylersommer.pro</email>

    <title>Professional Software Engineer</title>
    <description>Nine years of professional software engineering experience in demanding, fast-paced environments. Focus primarily in backend systems: infrastructure, e-commerce, payment processing platforms, and distributed systems. Strengths include problem solving, communication, technical writing, and systems administration. Passionate about open source software.</description>

    <profile>
        <section>Born and raised in the suburbs outside Salt Lake City, Utah, I got my first computer around 1998 when I was just ten years old. It was a beige Windows 95 machine and it opened doors to someplace magical.</section>
        <section>For Christmas a year or so later, I received my own copy of Microsoft Frontpage 2000. I recall building many terrible, terrible websites dedicated to Pok√©mon and Dragonball Z. Meager beginnings to what would become a successful career in software engineering.</section>
        <section>I landed my first professional coding gig in 2008, integrating landing pages with CRMs and CRMs with payment processors. Nine years later and I'm building resilient, distributed systems that operate on a global scale.</section>
        <section>Computing is a major passion of mine. I am constantly fascinated by all aspects of software engineering. I'm always in search of knowledge and application. These days, I spend most of my time learning how to be a dad. Otherwise, you'll find me coding, tinkering, and learning new things... or watching Rick and Morty.</section>
    </profile>

    <experience>
        <position>
            <company>Rakuten Marketing</company>
            <title>Software Engineer</title>
            <location>Midvale, UT</location>
            <from>2016</from>
            <to/>
            <description>
                <section>Responsible for maintenance, modernization, and new feature development for a distributed platform deployed in all parts of the world. Developed automated integrated testing framework to efficiently test the entire platform at scale.</section>
                <section>Developed and improved Hadoop, Hive, and Spark processes and related tooling for processing large amounts of data. Designed and developed Spark Streaming framework and related tooling.</section>
            </description>
        </position>

        <position>
            <company>Pronexis</company>
            <title>Senior Developer</title>
            <location>Spanish Fork, UT</location>
            <from>2015</from>
            <to>2016</to>
            <description>
                <section>Designed and built business and customer management software for service-based industries. Developed customer, truck routing, and sales team management systems.</section>
                <section>Responsible for maintaining and improving existing Symfony code-base. Implemented unit testing, integration testing, and continuous integration processes.</section>
            </description>
        </position>

        <position>
            <company>Terramar Labs</company>
            <title>Lead Developer</title>
            <location>San Diego, CA</location>
            <from>2012</from>
            <to>2015</to>
            <description>
                <section>Built software for small to medium businesses to help manage their internal processes and bottom line. Developed reporting and analytics tools, mobile kiosk applications, and web services.</section>
                <section>Engineered and contributed to many open source applications leveraged by Terramar Labs to manage code packages, code review, and payment processing.</section>
            </description>
        </position>

        <position>
            <company>PayRoll Innovations</company>
            <title>Lead Developer</title>
            <location>South Jordan, UT</location>
            <from>2010</from>
            <to>2012</to>
            <description>
                <section>Architected a payday advance loan processing system integrated with card issuing platforms. Implemented risk scoring algorithm to automatically qualify potential loan applicants based on various factors.</section>
                <section>Responsible for the maintenance of a small server cluster including primary and fail-over web and database servers.</section>
            </description>
        </position>

        <position>
            <company>NovaCare</company>
            <title>Developer / IT Manager</title>
            <location>Murray, UT</location>
            <from>2008</from>
            <to>2010</to>
            <description>
                <section>Integrated landing pages and various CRM platforms and payment processors. Maintained and improved legacy Visual Basic and Classic ASP fulfillment system. Implemented automation tools for managing high-volume printing and returns processing.</section>
                <section>Managed company-wide IT infrastructure and a small team of IT support personnel.</section>
            </description>
        </position>

        <extra>Expanded feature-set on a proprietary CRM/CMS system with a primary focus on fulfillment integration and and e-commerce reporting. Worked with small team of developers to improve performance and scalability.</extra>
        <extra>Designed and developed proprietary advertising tracking platform with single point of integration pixel placement and extensive reporting functionality.</extra>
        <extra>Built proof-of-concept photo mosaic generating app for iOS. Finished prototype was delivered and presented to several high profile clients with great reception.</extra>
        <extra>Maintainer of multiple open source projects. Responsible for libraries and applications handling payment processing, API consumption, templating, software package management, and pseudo-interactive chat participants.</extra>
    </experience>

    <qualifications>
        <attribute type="strength">Go</attribute>
        <attribute type="strength">Java</attribute>
        <attribute type="strength">Scala</attribute>
        <attribute type="strength">Ruby</attribute>
        <attribute type="strength">SQL</attribute>
        <attribute type="strength">Javascript</attribute>
        <attribute type="strength">PHP</attribute>
        <attribute type="needs-improvement">Swift</attribute>
        <attribute type="needs-improvement">Objective-C</attribute>
        <attribute type="needs-improvement">C</attribute>
        <attribute type="needs-improvement">C++</attribute>
        <attribute type="needs-improvement">Haskell</attribute>
        <attribute type="needs-improvement">Python</attribute>
        <attribute type="needs-improvement">C#</attribute>
        <attribute type="platform">AWS/GCP</attribute>
        <attribute type="platform">Linux</attribute>
        <attribute type="platform">Java EE</attribute>
        <attribute type="platform">PostgreSQL</attribute>
        <attribute type="platform">MySQL</attribute>
        <attribute type="platform">Apache Spark</attribute>
        <attribute type="platform">Hadoop</attribute>
        <attribute type="platform">Hive</attribute>
        <attribute type="platform">Cassandra</attribute>
    </qualifications>
</resume>
